AWSTemplateFormatVersion: "2010-09-09"
Description: CompLeap POC static site

Parameters:
  DomainName:
    Type: String
    Default: poc.compleap.testiopintopolku.fi
    Description: Unique FQDN for this website.
  HostedZoneName:
    Type: String
    Default: compleap.testiopintopolku.fi
    Description: Name of hosted zone where to create DNS record. Usually the parent domain of DomainName.
  CertificateArn:
    Type: String
    Description: ARN of certificate that signs the domain. Certificate must reside in us-east-1 due to CloudFront.

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html

  DomainNameRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "${DomainName}."
      Type: A

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: s3:GetObject
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${DomainName}/*"
          Principal: "*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref DomainName
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 60
          ForwardedValues:
            QueryString: false
          TargetOriginId: origin-bucket
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !GetAtt Bucket.DomainName
          Id: origin-bucket
          S3OriginConfig:
            OriginAccessIdentity: ""
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

Outputs:
  WebsiteURL:
    Value: !Sub "https://${DomainName}"
