export const NavigationEvent = Object.freeze({
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  PROFILE: 'PROFILE'
})

export const InteractionEvent = Object.freeze({
  TOGGLE_INTEREST: 'TOGGLE_INTEREST',
  SELECT_EDUCATION: 'SELECT_EDUCATION',
  CONFIRM_EDUCATION: 'CONFIRM_EDUCATION',
  CANCEL_EDUCATION: 'CANCEL_EDUCATION',
  ENTER_EDUCATION: 'ENTER_EDUCATION'
})
