export const NavigationEvent = Object.freeze({
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  PROFILE: 'PROFILE'
})

export const InteractionEvent = Object.freeze({
  TOGGLE_INTEREST: 'TOGGLE_INTEREST',
  SELECT_EDUCATION: 'SELECT_EDUCATION',
  SELECT_EDUCATION_SPECIFIER: 'SELECT_EDUCATION_SPECIFIER',
  CONFIRM_EDUCATION: 'CONFIRM_EDUCATION',
  CANCEL_EDUCATION: 'CANCEL_EDUCATION',
  BEGIN_EDUCATION_INPUT: 'BEGIN_EDUCATION_INPUT'
})
